insert into usuarios (username,password) values ('admin@ua.es','admin');
insert into usuarios (username,password) values ('adel@ua.es','adel');
insert into usuarios (username,password) values ('juan@ua.es','juan');
insert into multimedias (url,imgURL,title,description,creation_date)values ('https://seriesturcas.gratis/kemal-ve-nihan-amor-eterno-doblada/','Series/1/amoreterno.jpg','Amor eterno','"Amor Eterno". La trama se centra en la historia de Kemal Soydere, un hombre de clase trabajadora, y Nihan Sezin, una mujer de clase alta. A medida que su relación se desarrolla, se enfrentan a obstáculos sociales y familiares que amenazan su amor.','2024-01-20');
insert into multimedias (url,imgURL,title,description,creation_date)values ('https://pelisflix2.guide/serie/cobra-kai-zpzn/','Series/2/cobrakei.jpg','Cobra Kei','"Cobra Kai" es una serie de televisión que se centra en la rivalidad entre Johnny Lawrence y Daniel LaRusso, quienes ahora son adultos. Johnny reabre el dojo Cobra Kai, desencadenando una rivalidad renovada.','2024-01-10');
insert into multimedias (url,imgURL,title,description,creation_date)values ('https://seriesflix.lat/serie/elite-zszi/','Series/3/elite.jpg','Élite','"Élite" es una serie española que mezcla drama adolescente y misterio en un exclusivo colegio, explorando temas de desigualdad y secretos mientras un asesinato sacude la trama. Ha ganado popularidad a nivel mundial.','2024-01-01');
insert into multimedias (url,imgURL,title,description,creation_date)values ('https://pelisflix2.guide/pelicula/tenet-zefh/','Peliculas/1/tenet.jpg','Tenet','"Tenet" es una película de ciencia ficción de Christopher Nolan que sigue a un agente que lucha contra una amenaza global con manipulación del tiempo y secuencias de acción innovadoras. Destaca por su trama compleja y efectos visuales impactantes.','2024-01-21');
insert into multimedias (url,imgURL,title,description,creation_date)values ('https://pelisflix.news/pelicula/agente-stone/','Peliculas/2/agenteofstone.jpg','Heart of Stone','"Heartstone" es una película islandesa que sigue la amistad de dos jóvenes en un pueblo remoto, explorando la identidad y la sexualidad en un entorno conservador, con una sincera representación juvenil y destacadas actuaciones.','2024-01-20');
insert into multimedias (url,imgURL,title,description,creation_date)values ('https://pelisflix2.guide/pelicula/tenet-zefh/','Peliculas/1/tenet.jpg','Tenet','"Tenet" es una película de ciencia ficción de Christopher Nolan que sigue a un agente que lucha contra una amenaza global con manipulación del tiempo y secuencias de acción innovadoras. Destaca por su trama compleja y efectos visuales impactantes.','2024-01-20');
insert into multimedias (url,imgURL,title,description,creation_date)values ('https://pelisflix.news/pelicula/agente-stone/','Peliculas/2/agenteofstone.jpg','Heart of Stone','"Heartstone" es una película islandesa que sigue la amistad de dos jóvenes en un pueblo remoto, explorando la identidad y la sexualidad en un entorno conservador, con una sincera representación juvenil y destacadas actuaciones.','2024-01-20');
insert into series (seasons,year_end,year_start,destacada,fk_multimedia) values (2,2017,2015,true,1);
insert into series (seasons,year_end,year_start,destacada,fk_multimedia) values (5,0,2018,true,2);
insert into series (seasons,year_end,year_start,destacada,fk_multimedia) values (7,2023,2018,false,3);
insert into peliculas(duration_minutes,year_release,destacada,fk_multimedia) values (150,2020,false,4);
insert into peliculas(duration_minutes,year_release,destacada,fk_multimedia) values (122,2023,false,5);
insert into trailers(fk_multimedia) values (6);
insert into trailers(fk_multimedia) values (7);
insert into personas(nombre,imgURL) values ('Burak Ozcivit','Actores/1/BurakOzcivit.jpg');
insert into personas(nombre,imgURL) values ('Neslihan Atagul','Actores/2/NeslihanAtagul.jpg');
insert into personas(nombre,imgURL) values ('Kaan Urgancioglu','Actores/3/KaanUrgancioglu.jpeg');
insert into personas(nombre,imgURL) values ('Hazal Filiz','Actores/4/HazalFiliz.png');
insert into personas(nombre,imgURL) values ('Melisa Asli','Actores/5/MelisaAsli.jpg');
insert into personas(nombre,imgURL) values ('Hilal Saral','Actores/6/HilalSaral.jpg');
insert into personas(nombre,imgURL) values ('Ralph Macchio','Actores/7/RalphMacchio.jpg');
insert into personas(nombre,imgURL) values ('Xolo Maridueña','Actores/8/XoloMaridueña.jpg');
insert into personas(nombre,imgURL) values ('Mary Mouser','Actores/9/MaryMouser.jpg');
insert into personas(nombre,imgURL) values ('William Zabka','Actores/10/WilliamZabka.jpg');
insert into personas(nombre,imgURL) values ('Jon Hurwitz','Actores/11/JonHurwitz.jpg');
insert into personas(nombre,imgURL) values ('Hayden Schlossberg','Actores/12/HaydenSchlossberg.jpg');
insert into personas(nombre,imgURL) values ('Josh Heald','Actores/13/JoshHeald.jpg');
insert into personas(nombre,imgURL) values ('Ester Expósito','Actores/14/EsterExposito.jpg');
insert into personas(nombre,imgURL) values ('Itzan Escamilla','Actores/15/ItzanEscamilla.jpg');
insert into personas(nombre,imgURL) values ('Miguel Bernardeau','Actores/16/MiguelBernardeau.png');
insert into personas(nombre,imgURL) values ('Omar Ayuso','Actores/17/OmarAyuso.jpg');
insert into personas(nombre,imgURL) values ('Valentina Zenere','Actores/18/ValentinaZenere.jpg');
insert into personas(nombre,imgURL) values ('Carlos Montero Castiñeira','Actores/19/CarlosMonteroCastiñeira.jpg');
insert into personas(nombre,imgURL) values ('Darío Madrona','Actores/20/DaríoMadrona.jpg');
insert into personas(nombre,imgURL) values ('Elizabeth Debicki','Actores/21/ElizabethDebicki.jpg');
insert into personas(nombre,imgURL) values ('John David Washington','Actores/22/JohnDavidWashington.jpg');
insert into personas(nombre,imgURL) values ('Robert Pattinson','Actores/23/RobertPattinson.jpg');
insert into personas(nombre,imgURL) values ('Clémence Poésy','Actores/24/ClemencePoesy.jpg');
insert into personas(nombre,imgURL) values ('Christopher Nolan','Actores/25/ChristopherNolan.jpg');
insert into personas(nombre,imgURL) values ('Gal Gadot','Actores/26/GalGadot.jpg');
insert into personas(nombre,imgURL) values ('Alia Bhatt','Actores/27/AliaBhatt.jpg');
insert into personas(nombre,imgURL) values ('Jing Lusi','Actores/28/JingLusi.jpg');
insert into personas(nombre,imgURL) values ('Sophie Okonedo','Actores/29/SophieOkonedo.jpg');
insert into personas(nombre,imgURL) values ('Glenn Close','Actores/30/GlennClose.jpg');
insert into personas(nombre,imgURL) values ('Tom Harper','Actores/31/TomHarper.jpg');
insert into multimedia_actors(fk_multimedia,fk_actors) values(1,1);
insert into multimedia_actors(fk_multimedia,fk_actors) values(1,2);
insert into multimedia_actors(fk_multimedia,fk_actors) values(1,3);
insert into multimedia_actors(fk_multimedia,fk_actors) values(1,4);
insert into multimedia_actors(fk_multimedia,fk_actors) values(1,5);
insert into multimedia_creators(fk_multimedia,fk_creators) values(1,6);
insert into multimedia_actors(fk_multimedia,fk_actors) values(2,7);
insert into multimedia_actors(fk_multimedia,fk_actors) values(2,8);
insert into multimedia_actors(fk_multimedia,fk_actors) values(2,9);
insert into multimedia_actors(fk_multimedia,fk_actors) values(2,10);
insert into multimedia_creators(fk_multimedia,fk_creators) values(2,11);
insert into multimedia_creators(fk_multimedia,fk_creators) values(2,12);
insert into multimedia_creators(fk_multimedia,fk_creators) values(2,13);
insert into multimedia_actors(fk_multimedia,fk_actors) values(3,14);
insert into multimedia_actors(fk_multimedia,fk_actors) values(3,15);
insert into multimedia_actors(fk_multimedia,fk_actors) values(3,16);
insert into multimedia_actors(fk_multimedia,fk_actors) values(3,17);
insert into multimedia_actors(fk_multimedia,fk_actors) values(3,18);
insert into multimedia_creators(fk_multimedia,fk_creators) values(3,19);
insert into multimedia_creators(fk_multimedia,fk_creators) values(3,20);
insert into multimedia_actors(fk_multimedia,fk_actors) values(4,21);
insert into multimedia_actors(fk_multimedia,fk_actors) values(4,22);
insert into multimedia_actors(fk_multimedia,fk_actors) values(4,23);
insert into multimedia_actors(fk_multimedia,fk_actors) values(4,24);
insert into multimedia_creators(fk_multimedia,fk_creators) values(4,25);
insert into multimedia_actors(fk_multimedia,fk_actors) values(5,26);
insert into multimedia_actors(fk_multimedia,fk_actors) values(5,27);
insert into multimedia_actors(fk_multimedia,fk_actors) values(5,28);
insert into multimedia_actors(fk_multimedia,fk_actors) values(5,29);
insert into multimedia_actors(fk_multimedia,fk_actors) values(5,30);
insert into multimedia_creators(fk_multimedia,fk_creators) values(5,31);
insert into multimedia_actors(fk_multimedia,fk_actors) values(6,21);
insert into multimedia_actors(fk_multimedia,fk_actors) values(6,22);
insert into multimedia_actors(fk_multimedia,fk_actors) values(6,23);
insert into multimedia_actors(fk_multimedia,fk_actors) values(6,24);
insert into multimedia_creators(fk_multimedia,fk_creators) values(6,25);
insert into multimedia_actors(fk_multimedia,fk_actors) values(7,26);
insert into multimedia_actors(fk_multimedia,fk_actors) values(7,27);
insert into multimedia_actors(fk_multimedia,fk_actors) values(7,28);
insert into multimedia_actors(fk_multimedia,fk_actors) values(7,29);
insert into multimedia_actors(fk_multimedia,fk_actors) values(7,30);
insert into multimedia_creators(fk_multimedia,fk_creators) values(7,31);


